### PR TITLE
Spaceflights tutorial: data engineering -> data processing

### PR DESCRIPTION
**Pull request by AntonyMilneQB**
As per [popular demand](https://github.com/quantumblacklabs/private-kedro/pull/1006), we are changing "data engineering" modular pipeline to "data processing" in this example.

Tested out by doing `kedro run`; does exactly the same as before.

### CODE REVIEW

**Comment by MerelTheisenQB** [comment]
If we're changing data engineering to data processing in the spaceflights starter, should we do that for all starters?

**Comment by AntonyMilneQB** [comment]
> If we're changing data engineering to data processing in the spaceflights starter, should we do that for all starters?

I considered this and decided not to do so for now. My feeling is that the other starters probably should be updated in various ways (possibly including data engineering to data processing), but to save that for another time. Spaceflights is the only one where this is particularly important since it's a beginners tutorial, and the use of "data engineering" in the other starters is ok.

**Comment by MerelTheisenQB** [comment]
> I considered this and decided not to do so for now. My feeling is that the other starters probably should be updated in various ways (possibly including data engineering to data processing), but to save that for another time. Spaceflights is the only one where this is particularly important since it's a beginners tutorial, and the use of "data engineering" in the other starters is ok.

Cool, that makes sense ! 🙂

**Review by MerelTheisenQB — APPROVED** [review]

**Review by yetudada — APPROVED** [review]
Thank you so much @AntonyMilneQB!

**Pull request merged**
