### PR TITLE
Move credentials.yml from base to local

### PR DESCRIPTION
**Pull request by WaylonWalker**
I think there was a mistake to put credentials in base rather than local.  This change will align `mini-kedro` with the standard kedro template.

### CODE REVIEW

**Review by lorenabalan — APPROVED** [review]
Thank you for spotting this! I didn't think to check mini-kedro, I thought it wouldn't have credentials. Could you please also remove the line that says "THIS FILE MUST BE PLACED IN `conf/local`" ? :)

**Comment by WaylonWalker** [comment]
I noticed there were releases on the home page of the repo.  Doe this need to be rolled into a release?  I just did the PR against master thinking this was a simple fix and the starters were likely pulling straight from GitHub.  Is there anything extra/different to account for the releasing/versioning?

**Comment by lorenabalan** [comment]
This is fine. Releasing starters is just tagging a commit, and starter versions are matched with local kedro version installed. The changes on main Kedro and the starters will be synced up into the next release, 0.17.1.

**Review by limdauto — APPROVED** [review]

**Comment by limdauto** [comment]
Thanks @WaylonWalker. We have retagged 0.17.0 with this change so it's immediately available.

**Pull request merged**
