### PR TITLE
[KED-2128] Add `credentials.yml` to starters

### PR DESCRIPTION
**Pull request by lorenabalan**
Added file as per [line in docs](https://kedro.readthedocs.io/en/stable/02_get_started/05_example_project.html#what-best-practice-should-i-follow-to-avoid-leaking-confidential-data), although I'm not entirely sure why we used to do this rather than place it directly in `local/credentials.yml`. ❓ 

The links have been fixed already in all the `catalog.yml` files.

### CODE REVIEW

**Review by MerelTheisenQB — APPROVED** [review]
This looks good, but I'm also wondering why we add those files for the template in `conf/base` instead of directly in `conf/local`? Or is that because otherwise they wouldn't be pushed to github?

**Comment by lorenabalan** [comment]
> I'm also wondering why we add those files for the template in `conf/base` instead of directly in `conf/local`? 

I think we had a step in the tutorials to "move credentials to `local`", but not sure why not just have it there directly. I'm tempted to just make that change here before I merge, unless anyone has objections?

> Or is that because otherwise they wouldn't be pushed to github?

I saw we ignore everything `conf/**/credentials` so I wanna say it's safe to make the above change (need to fiddle with gitignore everytime anw).

**Comment by MerelTheisenQB** [comment]
I'm happy with moving it to `conf/local`.

**Review by limdauto — COMMENTED** [review]
I think we should move this to `conf/local` too. We probably don't need to worry about the tutorials because these starters are the end product and should be ready-to-go Kedro project.

**Comment by lorenabalan** [comment]
Done, moved to `local` and deleted the line that said "THIS SHOULD LIVE IN LOCAL". :)

**Review by MerelTheisenQB — APPROVED** [review]

**Review by limdauto — APPROVED** [review]

**Pull request merged**
