### PR TITLE
add simple starter

### PR DESCRIPTION
**Pull request by WaylonWalker**
## Simple
_a minimal kedro starter_

Based on a project currently running in "production" using GitHub actions [pypi-list](https://github.com/WaylonWalker/pypi-list).  It creates some [json output](https://pypi-list.waylonwalker.com/) for users to find English words that are available as a pypi package.

Simple is set up to use the following tools out of the box.

* pre-commit
* mypy
* sort
* flake8
* black
* interrogate

The goal of this starter is to create the most feature-complete, yet simple interface to get started with kedro.  It includes all the package analysis tools I would normally use.  The entire project resides essentially in one file with all the needed kedro components; the pipeline, nodes, catalog, and cli.  There are some features of kedro such as its cli that will not work, but the core components that make the Pipeline and Catalog will work fine.

Users can use this starter to create simple toy projects, learning, get started quickly on a project that may morph to a full project later, or anything that they would like to move quickly without sacrificing quality and features.

### CODE REVIEW

**Comment by datajoely** [comment]
Hi @WaylonWalker thank you for the contribution! I'm not sure I'd necessarily call this 'simple', I would maybe call it `standalone-code-api` what do you think?

**Comment by WaylonWalker** [comment]
> Hi @WaylonWalker thank you for the contribution! I'm not sure I'd necessarily call this 'simple', I would maybe call it `standalone-code-api` what do you think?

The essence of what I am trying to get here is a working minimal example to work from.  I have seen the default template trip up newcomers with the complexity that it brings to someone early in their python data science journey.  I do see that the word simple is a bit loaded.

Here is a brainstorm list of ideas, if you still would prefer `standalone-code-api` I would be ok with that as well.

* miniml 
* small
* single-file
* single-module
* single-code-api
* standalone
* standalone-code-api

**Review by lorenabalan — CHANGES_REQUESTED** [review]
Hi @WaylonWalker , thank you for raising this. We've thought about the discoverability of starters and this is what we've come up with:

In order to not add a maintainability burden, we don't plan to host/support both kedro team maintained and community-contributed starters on this repo. Can I suggest instead that you host this on a separate repo, and tag it with a `kedro-starter` topic? Then feel free to add the link to that repo both here in the README.md, as well as in the kedro codebase to the output of the `kedro starter list` CLI command.

⚡ The ideal future state is that we would search on GitHub for repos with `kedro-starter` topic, and list them out dynamically (maybe ordered by number of stars) using `kedro starter list`. In the meantime though, a static list will do, while we prioritise other features.

Hope this makes sense. 🙂

**Comment by WaylonWalker** [comment]
Totally makes sense.

**Pull request closed without merging**
